services:
  db:
    image: postgres:17
    container_name: db_todo_app
    restart: no
    shm_size: 128mg
    ports:
      - 5430:5432
    environment:
      - POSTGRES_DB:todo_app 
      - POSTGRES_USER:admin
      - POSTGRES_PASSWORD:123456
    volumes:
      - ./postgres:/var/lib/postgresql/data